### ISSUE TITLE
[BUG] - Cors not working when using optional parameters

### ISSUE THREAD

**Issue by sujit-baniya** [hertz-contrib/cors#5]
```go
package main

import (
	"context"
	"github.com/hertz-contrib/cors"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

func main() {
	h := server.Default(server.WithHostPorts(":3000"))
	h.Use(cors.New(cors.Config{AllowAllOrigins: true}))

	h.POST("/login/*provider", func(c context.Context, ctx *app.RequestContext) {
		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
	})
	h.Spin()
}
```

**Comment by li-jin-gou** [comment]
Hi @sujit-baniya Can you provide me with the CURL request command?

**Comment by sujit-baniya** [comment]
@li-jin-gou 

```curl
curl 'http://localhost:3001/login' \
  -H 'sec-ch-ua: "Brave";v="113", "Chromium";v="113", "Not-A.Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36' \
  -H 'Content-Type: application/json' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Referer: http://localhost:3333/' \
  -H 'x-request-id: 6c9a49c1a540d282e01ccc81e391cab194dfa491a53cd838ed7e3bb6d1eee62e' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --data-raw '{"username":"test@hotmail.com","password":"hello@there","remember_me":true}' \
  --compressed

```

This is CURL request but I'm unable to replicate the issue with Curl.

The issue is replicated when making request via JS. Here's a video for the issue.
https://www.loom.com/share/85716c7c8ad147e0b83f600780171945

**Comment by li-jin-gou** [comment]
I will try to reproduce it locally.

**Comment by fineCoderWithLove** [comment]
`package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"
	"go.uber.org/zap"
	"qiniu/cmd/api/db"
	"qiniu/cmd/api/router"
	"qiniu/cmd/api/rpc"
)
func main() {
	h := server.New(
		server.WithHostPorts("0.0.0.0:8080"),
		server.WithHandleMethodNotAllowed(true),
	)
	h.Use(cors.New(cors.Config{
		AllowAllOrigins: true,
	}))
	logger, _ := zap.NewDevelopment()
	db.Init()                  //redis
	zap.ReplaceGlobals(logger) //日志
	rpc.InitRPC()              //rpc
	router.Init(h)             //路由

	h.Spin()
}
`
`    window.onload = function demo() {
      // 使用fetch API发送GET请求    
      fetch('http://192.168.1.109:8080/qiniu/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTg2NjQxNDUsInBhc3N3b3JkIjoiJHBia2RmMi1zaGE1MTIkQm1uR0V1WlJRYWk5QjRzOSRiM2FhODlkMGYzM2E2MmRlZTkzZWQyMzU2NDRkM2NlYTQxODYwMTI1MzdhOTM2ODBlNWI4MDFmYmJkNjNlYWQyIiwidXNlcm5hbWUiOiJmdWNrIn0.lT3eVf-j6HA46J51T-f6WNBwkfviK7bResot96ifVMg&user_id=27', {
          method: 'GET', // 请求方法    
          headers: {
            'Access-Control-Allow-Origin': '*', // 添加CORS头部字段    
          },
        })
        .then(response => {
          if (!response.ok) {
            throw new Error('网络响应不是ok');
          }
          return response.json(); // 解析返回的JSON数据    
        })
        .then(data => {
          // 处理返回的数据    
          console.log(data);
        })
        .catch(error => {
          // 处理请求中的错误    
          console.error('请求发生错误:', error);
        });
    }`
仍然出现跨域问题
![image](https://github.com/hertz-contrib/cors/assets/122780660/2ce9170a-3242-4410-9183-93075a246244)

**Comment by fineCoderWithLove** [comment]
```
package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"
	"go.uber.org/zap"
	"qiniu/cmd/api/db"
	"qiniu/cmd/api/router"
	"qiniu/cmd/api/rpc"
)

// biz/router/middleware/cors.go

func main() {
	h := server.New(
		server.WithHostPorts("0.0.0.0:8080"),
		server.WithHandleMethodNotAllowed(true),
	)
	h.Use(cors.New(cors.Config{
		AllowAllOrigins: true,
	}))
	logger, _ := zap.NewDevelopment()
	db.Init()                  //redis
	zap.ReplaceGlobals(logger) //日志
	rpc.InitRPC()              //rpc
	router.Init(h)             //路由

	h.Spin()
}

```
```
    window.onload = function demo() {
      // 使用fetch API发送GET请求    
      fetch('http://192.168.1.109:8080/qiniu/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTg2NjQxNDUsInBhc3N3b3JkIjoiJHBia2RmMi1zaGE1MTIkQm1uR0V1WlJRYWk5QjRzOSRiM2FhODlkMGYzM2E2MmRlZTkzZWQyMzU2NDRkM2NlYTQxODYwMTI1MzdhOTM2ODBlNWI4MDFmYmJkNjNlYWQyIiwidXNlcm5hbWUiOiJmdWNrIn0.lT3eVf-j6HA46J51T-f6WNBwkfviK7bResot96ifVMg&user_id=27', {
          method: 'GET', // 请求方法    
          headers: {
            'Access-Control-Allow-Origin': '*', // 添加CORS头部字段    
          },
        })
        .then(response => {
          if (!response.ok) {
            throw new Error('网络响应不是ok');
          }
          return response.json(); // 解析返回的JSON数据    
        })
        .then(data => {
          // 处理返回的数据    
          console.log(data);
        })
        .catch(error => {
          // 处理请求中的错误    
          console.error('请求发生错误:', error);
        });
    }
```
路由配置:r.GET("/qiniu/publish/list", middleware.LoginMiddleware(), handler.QueryPublistList)
仍然出现
Access to fetch at 'http://192.168.1.109:8080/qiniu/ from origin 'null' has been blocked by CORS policy: Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by Skyenought** [comment]
@fineCoderWithLove 请给我一个能够复现问题的 demo, 你之前提供的太简略了

**Comment by fineCoderWithLove** [comment]
你好，我昨天晚上已经解决了这个问题，是我在CROS中只配置了AllowAllOrigins = true 导致的跨域问题





长安少年
***@***.***




这样配置 以后，没有产生跨域




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hertz-contrib/cors"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月1日(星期三) 晚上11:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hertz-contrib/cors] [BUG] - Cors not working when using optional parameters (Issue #5)





 
@fineCoderWithLove 请给我一个能够复现问题的 demo, 你之前提供的太简略了

**Comment by sujit-baniya** [comment]
@fineCoderWithLove Can you share the code?

**Comment by fineCoderWithLove** [comment]
I have no problem configuring CORS in the Windows 10 environment like this
h.Use(cors.New(cors.Config{
    //准许跨域请求网站,多个使用,分开,限制使用*
    AllowOrigins: []string{"*"},
    //准许使用的请求方式
    AllowMethods: []string{"PUT", "PATCH", "POST", "GET", "DELETE"},
    //准许使用的请求表头
    AllowHeaders: []string{"Origin", "Authorization", "Content-Type"},
    //显示的请求表头
    ExposeHeaders: []string{"Content-Type"},
    //凭证共享,确定共享
    AllowCredentials: true,
    //容许跨域的原点网站,可以直接return true就万事大吉了
    AllowOriginFunc: func(origin string) bool {
       return true
    },
    //超时时间设定
    MaxAge: 24 * time.Hour,
}))



长安少年
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hertz-contrib/cors"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月2日(星期四) 中午12:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hertz-contrib/cors] [BUG] - Cors not working when using optional parameters (Issue #5)





 
@fineCoderWithLove Can you share the code?
